Aif22
Toeller/HHBK_Chemicals pull request #157
Opened 2020-12-01 17:47 UTC by Radi-A

Um ViewFertigung und IControllerLagerverwaltung ergänzt

2020-12-01 17:48 UTC, Toeller requested changes
Brache ich nicht. Bitte löschen

2020-12-01 17:51 UTC, Toeller approved these changes
ViewFertigung.cs nehme ich, aber es fehlt das eigentliche Fenster... ViewFertigung.Designer.cs und ViewFertigung.resx

2020-12-01 17:53 UTC, Toeller approved these changes

2020-12-01 17:55 UTC, Toeller commented
Bitte ändern und nochmal einen Pullrequest.

2020-12-01 17:55 UTC, closed without merging

2020-12-03 20:38 UTC, MichailiK commented
Schönen Job mit den Delete commit ([cf2c76f](https://github.com/Toeller/HHBK_Chemicals/pull/157/commits/cf2c76f8b2288456a2e78f275d848bc381c4f3db),) der hat das gerade gepullt & jetzt ist seine AIF22-Branch am Arsch, da ja jetzt die Projektdatei weg ist & er das Projekt nun nicht mehr laden kann.
Ich werde, sobald ich es kann, seine AIF22 Branch auf [2846761e](https://github.com/Toeller/HHBK_Chemicals/commit/2846761edf0f6e56d44872be013a6f30804541c7) (oder was auch immer das neuste commit in der AIF22-Branch sein wird) hard-resetten.